[bootstrap.packages]
"apt:build-essential" = "latest"
"apt:cmake" = "latest"
"apt:fzf" = "latest"
"apt:gdu" = "latest"
"apt:hstr" = "latest"
"apt:jq" = "latest"
"apt:lazygit" = "latest"
"apt:libsecret-1-0" = "latest"
"apt:libsecret-1-dev" = "latest"
"apt:powerline-go" = "latest"
"apt:pre-commit" = "latest"
"apt:python3-dev" = "latest"
"apt:silversearcher-ag" = "latest"
"apt:tig" = "latest"
"apt:tree" = "latest"
"apt:ugrep" = "latest"
"apt:universal-ctags" = "latest"
"apt:unzip" = "latest"
"apt:whois" = "latest"
"apt:zoxide" = "latest"
"aqua:cantino/mcfly" = "latest"

[bootstrap.repos]                      # git repos cloned before dotfiles
"~/Code/pragmatic/dotfiles" = { url = "git@github.com:pragmatic/dotfiles.git", ref = "main" }

[settings]
dotfiles.root = "~/Code/pragmatic/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]                             # dotfiles: symlink/copy/template
 # "~/.config/nvim" = {}
"~/.bash_profile" = {}
"~/.config/lazygit/config.yml" = {}
"~/.config/mise/config.yml" = {}
"~/.gitattributes" = {}
"~/.gitconfig" = {}
"~/.inputrc" = {}
"~/.lesskey" = {}
"~/.tigrc" = {}
"~/.tmux.conf" = {}
"~/.vim/colors/inatick.vim" = {}
"~/.vimrc" = {}

# [tasks.bootstrap]                      # anything else, with tools on PATH
# description = "Install or update Vim plugins headlessly"
# run = "vim --noplugin -u ~/.vimrc +PlugInstall +qall"
[env]
_.path = ["~/bin"]
