[bootstrap.packages]
"apt:bc" = "latest"
"apt:build-essential" = "latest"
"apt:cmake" = "latest"
"apt:fzf" = "latest"
"apt:gdu" = "latest"
"apt:hstr" = "latest"
"apt:jq" = "latest"
"apt:lazygit" = "latest"
"apt:libsecret-1-0" = "latest"
"apt:libsecret-1-dev" = "latest"
"apt:ncal" = "latest"
"apt:powerline-go" = "latest"
"apt:pre-commit" = "latest"
"apt:python3-dev" = "latest"
"apt:silversearcher-ag" = "latest"
"apt:sqlite3" = "latest"
"apt:tig" = "latest"
"apt:tmux" = "latest"
"apt:tree" = "latest"
"apt:ugrep" = "latest"
"apt:universal-ctags" = "latest"
"apt:unzip" = "latest"
"apt:whois" = "latest"
"apt:zoxide" = "latest"

[bootstrap.repos]                      # git repos cloned before dotfiles
"~/Code/pragmatic/dotfiles" = { url = "git@github.com:pragmatic/dotfiles.git", ref = "main" }

[dotfiles]                             # dotfiles: symlink/copy/template
 # "~/.config/nvim" = {}
"~/.bash_profile" = {}
"~/.config/lazygit/config.yml" = {}
"~/.config/mise/config.linux.toml" = {}
"~/.config/mise/config.toml" = {}
"~/.config/mise/miserc.toml" = {}
"~/.gitattributes" = {}
"~/.gitconfig" = {}
"~/.inputrc" = {}
"~/.lesskey" = {}
"~/.tigrc" = {}
"~/.tmux.conf" = {}
"~/.vim/autoload/plug.vim" = {}
"~/.vim/colors/inatick.vim" = {}
"~/.vimrc" = {}

[env]
CLICOLOR = true
GROFF_NO_SGR = 1
MCFLY_FUZZY = 3

[settings]
dotfiles.root = "~/Code/pragmatic/dotfiles"
dotfiles.default_mode = "symlink"

[shell_alias]
cdr = "cd $(git rev-parse --show-toplevel)"

[tasks.bootstrap]                      # Run with mise run bootstrap
description = "Install or update Vim plugins headlessly"
run = "vim --noplugin -u ~/.vimrc +PlugInstall +qall"

[tools]
"aqua:cantino/mcfly" = "latest"
"github:k1LoW/mo" = "latest"
"github:legal90/awscurl" = "latest"
"github:mikefarah/yq" = "latest"
"github:starship/starship" = "latest"
"github:terraform-docs/terraform-docs" = "latest"
"pipx:awsume" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
doggo = "latest"
fnox = "latest"
gh = "latest"
ghorg = "latest"
go = "latest"
pipx = "latest"
python = "latest"
usage = "latest"
