[bootstrap.packages]
"apt:bc" = "latest"
"apt:btop" = "latest"
"apt:build-essential" = "latest"
"apt:cmake" = "latest"
"apt:fzf" = "latest"
"apt:gdu" = "latest"
"apt:hstr" = "latest"
"apt:ipcalc" = "latest"
"apt:jq" = "latest"
"apt:lazygit" = "latest"
"apt:libsecret-1-0" = "latest"
"apt:libsecret-1-dev" = "latest"
"apt:libnss-mdns" = "latest"
"apt:mgitstatus" = "latest"
"apt:ncal" = "latest"
"apt:powerline-go" = "latest"
"apt:pre-commit" = "latest"
"apt:python3-dev" = "latest"
"apt:rsync" = "latest"
"apt:silversearcher-ag" = "latest"
"apt:sqlite3" = "latest"
"apt:tig" = "latest"
"apt:tmux" = "latest"
"apt:tcptraceroute" = "latest"
"apt:traceroute" = "latest"
"apt:tree" = "latest"
"apt:ugrep" = "latest"
"apt:universal-ctags" = "latest"
"apt:unzip" = "latest"
"apt:whois" = "latest"
"apt:zoxide" = "latest"

[env]
POWERLINE_GO_MODULES_BASE = "aws,ssh,host,cwd,dotenv,perms,git,exit"

[shell_alias]
# Specific alias override for linux x64
tofu = "terraform"
